### PR TITLE
FRN module sound clips

### PR DESCRIPTION
**Pull request by sh123**
Missing sounds clips for FRN module. Tested with svxlink frn converting with filter_sounds.sh beforehand.

### CODE REVIEW

**Comment by sm0svx** [comment]
Maybe I should have listened to the sound clips before I merged them, but the clips you generated does not sound like Heather. Are you sure these are the clips you generated from Acapela Box using the Heather voice?  They are of slightly lower quality and the voice is different.

What worries me is if the clips come from another voice synthesizer, then the licensing may be unclear and I may not be allowed to redistribute them publicly.

**Comment by sh123** [comment]
These are settings which were in use, are they ok? I will regenerate one more time when will be next to computer.. maybe picked wrong voice from "Select a voice"

acapella

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment's screen shot and created new pull request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Comment by sh123** [comment]
Regenerated sounds using settings from previous comment screen shot and created new please request, please, check.

**Pull request merged**
